package de.uni.freiburg.iig.telematik.swat.workbench.properties;

public enum SwatProperty {
	
	WORKING_DIRECTORY,
	KNOWN_WORKING_DIRECTORIES,
	PRISM_PATH,
	REQUIRE_NET_TYPE,
	VERIFY_PNML_SCHEMA, 
	ICON_SIZE, 
 SCIFF_PATH, LOLA_PATH, ARISTA_FLOW_URL, ARISTA_FLOW_USER, ARISTA_FLOW_PASS, NET_FOLDER_NAME, LOG_FOLDER_NAME;

}
