package de.uni.freiburg.iig.telematik.swat.workbench.properties;

public enum SwatProperty {
	
	WORKING_DIRECTORY,
	KNOWN_WORKING_DIRECTORIES,
	
	SCIFF_PATH, 
	LOLA_PATH, 
	PRISM_PATH,
	ARISTA_FLOW_URL, ARISTA_FLOW_USER, ARISTA_FLOW_PASS,
	
	REQUIRE_NET_TYPE,
	VERIFY_PNML_SCHEMA, 
	ICON_SIZE,
	
	DEFAULT_RES_CONTEXT,DEFAULT_TIME_CONTEXT
}
